### ISSUE TITLE
Add E-Mail Responder

### ISSUE THREAD

**Issue by emilelm96** [apeinot/DD2480_lab2_group18#2]
**Is your feature request related to a problem? Please describe.**
Notifying the corresponding users by e-mail when they push their code.

**Describe the solution you'd like**
Notify the corresponding user of the status of their pushed commits by e-mail, i.e. the complete output of the ant tests on the pushed code; if the tests passed or not and so on.

**Comment by emilelm96** [comment]
I could add the option of sending the same mail to multiple recipients with one function call, if we want that.

**Comment by apeinot** [comment]
Currently it is not really needed. But if we decide to do so, you will have to create a new issue for that purpose.
