### ISSUE TITLE
Add main handle method

### ISSUE THREAD

**Issue by Jonagoo** [apeinot/DD2480_lab2_group18#5]
**Description of the problem**
Handle method does not perform Continuous Integration tasks on incoming requests.

**Description of the solution**
Add function calls to handle for fetching/running code, parsing request etc.

**Comment by apeinot** [comment]
I think the following succession of command should be executed in the CI process:

git clone $url_repo

In $repo_directory: (specify it when calling execute)
git checkout $commit_id
ant compile
ant test-compile
ant test

rm -r $repo_directory

(Only consider the result from the 3 ant command for the return status)
